FROM fedora:latest

RUN dnf -y install systemd dbus python3 python3-pip python3-virtualenv python3-pytest iproute iputils && dnf clean all

COPY container-tests.service /etc/systemd/system
RUN ln -s /etc/systemd/system/container-tests.service /etc/systemd/system/multi-user.target.wants/container-tests.service

STOPSIGNAL SIGRTMIN+3

CMD /usr/sbin/init
